// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using RoadGuard.CadParser.Data;

#nullable disable

namespace RoadGuard.CadParser.Migrations
{
    [DbContext(typeof(RoadGuardDbContext))]
    [Migration("20260926060454_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoadGuard.CadParser.Entities.CadDrawing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("ParsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Srid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CadDrawings", (string)null);
                });

            modelBuilder.Entity("RoadGuard.CadParser.Entities.CadGeometryFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CadDrawingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("LayerColor")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LayerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CadDrawingId")
                        .HasDatabaseName("IX_CadGeometryFeatures_CadDrawingId");

                    b.ToTable("CadGeometryFeatures", (string)null);
                });

            modelBuilder.Entity("RoadGuard.CadParser.Entities.CadGeometryFeature", b =>
                {
                    b.HasOne("RoadGuard.CadParser.Entities.CadDrawing", "CadDrawing")
                        .WithMany("GeometryFeatures")
                        .HasForeignKey("CadDrawingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CadDrawing");
                });

            modelBuilder.Entity("RoadGuard.CadParser.Entities.CadDrawing", b =>
                {
                    b.Navigation("GeometryFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
