using System;
using System.Collections.Generic;

namespace RoadGuard.CadParser.Entities
{
    /// <summary>
    /// Represents the metadata of an uploaded and parsed CAD drawing.
    /// One CadDrawing maps to one uploaded DXF file.
    /// </summary>
    public sealed class CadDrawing
    {
        /// <summary>Primary key (Guid, generated by the application).</summary>
        public Guid Id { get; set; }

        /// <summary>Original filename as provided by the caller (max 512 chars).</summary>
        public string FileName { get; set; } = string.Empty;

        /// <summary>UTC timestamp of when parsing completed.</summary>
        public DateTime ParsedAtUtc { get; set; }

        /// <summary>
        /// Spatial Reference ID applied to all geometries in this drawing.
        /// Supported: 4326 (WGS-84), 32648 (UTM 48N), 32649 (UTM 49N).
        /// </summary>
        public int Srid { get; set; }

        // ------------------------------------------------------------------ //
        //  Navigation                                                          //
        // ------------------------------------------------------------------ //

        /// <summary>All geometry features extracted from this drawing.</summary>
        public ICollection<CadGeometryFeature> GeometryFeatures { get; set; }
            = new List<CadGeometryFeature>();
    }
}
