using System;
using NetTopologySuite.Geometries;

namespace RoadGuard.CadParser.Entities
{
    /// <summary>
    /// Represents a single geometric entity extracted from a CAD drawing.
    /// The Geometry column uses SQL Server native geometry type via NTS + EF Core spatial extension.
    /// </summary>
    public sealed class CadGeometryFeature
    {
        /// <summary>Primary key (Guid, generated by the application).</summary>
        public Guid Id { get; set; }

        /// <summary>Foreign key referencing the parent CadDrawing.</summary>
        public Guid CadDrawingId { get; set; }

        /// <summary>AutoCAD layer name (e.g. "ROAD", "0").</summary>
        public string LayerName { get; set; } = string.Empty;

        /// <summary>
        /// Layer color as a display string, e.g. "ByLayer", "Red", "ACI:5".
        /// Nullable because color is not always present.
        /// </summary>
        public string? LayerColor { get; set; }

        /// <summary>
        /// NTS Geometry stored in SQL Server as a geometry column.
        /// Can be Point, LineString, Polygon, etc.
        /// SRID is set from the parent drawing Srid.
        /// </summary>
        public Geometry Geometry { get; set; } = null!;

        // ------------------------------------------------------------------ //
        //  Navigation                                                          //
        // ------------------------------------------------------------------ //

        /// <summary>Parent drawing this feature belongs to.</summary>
        public CadDrawing CadDrawing { get; set; } = null!;
    }
}
